### ISSUE TITLE
problems running the testing video 

### ISSUE THREAD

**Issue by wanghlv** [HanLab-OSU/MouseActivity#1]
Hi, I keeps getting the error message "Error using MouseActivity5 (line 180)
Frame Range must be a 1x2 vector of frame indexes with the first value less than or equal to the second value.". Could you help me how to resolve this? Thanks
Hsiao-Lin

**Comment by pmathews8** [comment]
Decrease the value for the number of frames. It works when I drop it to 5000

**Comment by pmathews8** [comment]
I can't get this to work with any of my own videos. Both mp4 and mov. I get the following error.  
Error using MouseActivity5 (line 50)
Frame index must be a numeric value greater than zero and less than or equal to the number of frames in
the file.

**Comment by HanLab-OSU** [comment]
I updated the line 50. The reason was that the initial random frame picked up was greater than the total frames you have in your video file.
