### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by matinsaba** [HanLab-OSU/MouseActivity#4]
I have tried to run the code but I have gotten the errors below: 
Error using xlwrite (line 93)
The POI library is not loaded in Matlab.
Check that POI jar files are in Matlab Java path!

        Error using xlwrite (line 93)
        xlwrite([dirpath1 video_name '/' xlsfilename],titlerow,mouse,'A1');
        analysis(filename, dirpath);

**Comment by HanLab-OSU** [comment]
As it says, please make sure you also download the poi_library folder and put it into your folder that contains the MouseActivity5.m and xlwrite.m files.
